# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ae3b6047a2cf9b51dadcffed84021793c8f7b1834087629d35f3a9e708875d78d9637c10c8fcf218178d6444b13976c937f54f553fc066ca4c761a4e4e0e49d

test:
  secret_key_base: 3503ab547af66d425a5d352087f5f1c8047715cede12e44f2bf459d0da21b5989a9b14f3a609d324d08d5de5925e6bb2e0c21ff22c10e4602bef85f31a966884

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
